spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://login.microsoftonline.com/${TENANT_ID}/v2.0
          jwk-set-uri: https://login.microsoftonline.com/common/discovery/v2.0/keys

  datasource:
    driver-class-name: ${DB_NAME}
    url: ${DB_URL}
    username: ${DB_USER_NAME}
    password: ${DB_PASSWORD}
  h2:
    console:
      enabled: true
app:
  jwt:
    secret: "t6PdFmBbia3rZVk9ecbHTufjtwnb95JW"
    expiration-time: 3600
logging:
  level:
    org:
      springframework:
        security: info
        web: info